### ISSUE TITLE
Who else is "in/on"

### ISSUE THREAD

**Issue by koalie** [SolidOS/solid-panes#1]
Wouldn't it be nice, if like etherpad or Google Docs, you had a way of knowing that other people are using the app, and who? e.g. in Shared Notes, who is grey, blue and orange.

**Comment by timbl** [comment]
Agreed

**Comment by timbl** [comment]
Added code to track and list who uses it, with the color they type in. In rev 822eb4ce664aa6b385ef1d956640adb9bae37257
