### ISSUE TITLE
Add feature to data browser allowing user to edit index.html root 

### ISSUE THREAD

**Issue by mikeadams1** [SolidOS/solid-panes#132]
Create feature to edit the source code in the data browser for the root index.html page.

**Comment by Vinnl** [comment]
I think this might actually already be possible, using the Dokieli pane? But perhaps someone else can confirm, as I'm not too familiar with it.

**Comment by mikeadams1** [comment]
I would want to use the data browser source code feature to do it.

**Comment by mikeadams1** [comment]
As an example, if you go to profile/card and click user account listed under storage or account, will bring up the root home page index.html in the data browser however, it will not let you save any edits you make to the source code, throws 500 error, can we allow edits here of the root index.html?

**Comment by mikeadams1** [comment]
I’m not opposed to using Dokieli as an editor For certain things, more like documents, stuff like that, and although you can edit source code with it I would preferred to edit the source code of the root index.HTML through the data browser.

**Comment by mikeadams1** [comment]
https://github.com/solid/node-solid-server/issues/1278

**Comment by mikeadams1** [comment]
Feature created, can now edit root index.html via data browser source code. @Vinnl
