### ISSUE TITLE
Add link to delete user profile from basicPreferences

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#146]
This builds upon https://github.com/solid/solid-panes/issues/144.

This should add the link that allows users to delete their accounts and Pods on NSS.

(This used to be shown for authenticated users on the generated index.html that we had for NSS before.)

**Comment by megoth** [comment]
Handle situation where you have multiple Pods - give a link to each Pod's account management page.

**Comment by Vinnl** [comment]
Hmm, so there are two open questions for this:

1. How do we determine the deletion link? We can use `<pim:storage>/account/delete` for now to hardcode the NSS path, but:
2. How do we differentiate between single-/multi-user setups? i.e. if `pim:storage` is `https://vincent.dev.inrupt.net` and it's a multi-user setup, the NSS link would be `https://dev.inrupt.net/account/delete`, but if is a single-user setup at that location, then the link would be `https://vincent.dev.inrupt.net/account/delete`...

If we're assuming 1 already, maybe assume multi-user as well?

**Comment by megoth** [comment]
> 1. How do we determine the deletion link? We can use `<pim:storage>/account/delete` for now to hardcode the NSS path, but:

We have to get this standardized, but for now we assume that the server running is NSS. Once we start working on IPS, we can see which URI they have, and then we _could_ do a `HEAD` request to both URIs to check which one exist.

It's a bad solution, but the only one I think we can implement for now.

> 2. How do we differentiate between single-/multi-user setups? i.e. if `pim:storage` is `https://vincent.dev.inrupt.net` and it's a multi-user setup, the NSS link would be `https://dev.inrupt.net/account/delete`, but if is a single-user setup at that location, then the link would be `https://vincent.dev.inrupt.net/account/delete`...
> 
> If we're assuming 1 already, maybe assume multi-user as well?

I think we have to assume multi-user for now, but we could of course try the check-if-exist trick as I proposed earlier as well. Again, it's a bad solution, but hopefully better than nothing.

**Comment by Vinnl** [comment]
Code that assumes NSS and single-user mode is now available at https://github.com/solid/solid-panes/tree/146-delete-profile.

**Comment by megoth** [comment]
Btw, I've tried starting some work on [account management standardization on the Data Interoperability Panel](https://github.com/solid/data-interoperability-panel/issues/18).
