### ISSUE TITLE
weird error on my public folder while logged in

### ISSUE THREAD

**Issue by michielbdejong** [SolidOS/solid-panes#183]
<img width="943" alt="Screenshot 2019-10-03 12 08 46" src="https://user-images.githubusercontent.com/408412/66118430-a4134880-e5d6-11e9-9f5e-6369e5630b1e.png">

**Comment by megoth** [comment]
I suspect this might be because you have a file with an illegal character - did you create a resource with colon in the name?

**Comment by michielbdejong** [comment]
this is viewing the public folder, if one of the file names in there is not displayable then it should just omit that one or show it greyed out or something, right?

You can see the exact filenames in my public folder by running:
```sh
curl https://michielbdejong.inrupt.net/public/
```
As you can see, one filename in there which I hope is not illegal is `chat_Mitzi László`

**Comment by megoth** [comment]
`chat_Mitzi László` is not a problem on my local development setup, at least. But I cannot see any apparent culprit for this in the TTL-response for https://michielbdejong.inrupt.net/public/ either =/

Lets check this after we've done an update of the latest mashlib to inrupt.net, should be done during the day.

**Comment by michielbdejong** [comment]
Still seeing the same error there, also when not logged in. Do you?

**Comment by michielbdejong** [comment]
This is what @Vinnl sees when trying to view my public folder in Firefox https://files.gitter.im/solid/data-browser/pTr0/image.png

**Comment by bourgeoa** [comment]
As I saw a folder named `http:` I reproduced the bug by creating a folder with a URI name ex: http://www.w3.org
then 2 folders are created "http:" and "www.w3.org". 
In fact the problem also arise with `test:test` so it seems that you cannot use `":"` in a folder name

**Comment by brownhoward** [comment]
Hi @bourgeoa,

The bug with colons in the resource (folder or data) name is a known issue (https://github.com/solid/solid-panes/issues/178). It is currently being investigated/fixed and will be included in an upcoming release.

**Comment by michielbdejong** [comment]
Great! Then we can close this one as a duplicate of #178.

**Comment by michielbdejong** [comment]
gitter conversation about this:

<img width="445" alt="Screenshot 2019-10-14 08 46 22" src="https://user-images.githubusercontent.com/408412/66733256-3b8e5c00-ee5f-11e9-914f-f0d22edef65a.png">

See https://gitter.im/solid/data-browser?at=5da05d8f65dd8569a0ba0a01
