### ISSUE TITLE
Long Chat: index.ttl not editable

### ISSUE THREAD

**Issue by brownhoward** [SolidOS/solid-panes#189]
When attempting to have a Long Chat with another user, when attempting to access a Long Chat resource of another user, I receive an error:
```
Error: Error recording your partipation: Exception in update: Error: Update: Can't make changes in uneditable <https://suser.solid.community/public/My%20Long%20Chat/index.ttl> Error: Update: Can't make changes in uneditable <https://suser.solid.community/public/My%20Long%20Chat/index.ttl> https://suser.solid.community/mashlib.min.js:1:29729 update https://suser.solid.community/mashlib.min.js:29:8415 a.pad.participationObject/< https://suser.solid.community/mashlib.min.js:29:7938 a.pad.participationObject https://suser.solid.community/mashlib.min.js:123:192709 getPreferencesForClass/</< undefined
```

## To Replicate
1. For User 1, create a new Long Chat in their /public folder.
2. Share the URL to the Long Chat with User 2.
3. User 2 attempts to open the Long Chat.

## Expected Behaviour
1. The Long Chat is displayed.

## Actual Behaviour
1. Error message in issue description displayed.

**Comment by megoth** [comment]
Could you check if this is still the case on dev.inrupt.net? (I was not able to reproduce it.)

**Comment by brownhoward** [comment]
I can no longer replicate on dev.inrupt.net. When the chat invitee accesses the Long Chat, it is displayed correctly.
