### ISSUE TITLE
Long Chat: 403 Error when attempting to add message

### ISSUE THREAD

**Issue by brownhoward** [SolidOS/solid-panes#190]
When attempting to add a chat message to a Long Chat on another User's Pod, when I click the 'Enter' icon nothing appears to happen. However, a series of errors are displayed in the Console:
```
index.js.1405
PUT https://khoward.dev.inrupt.net/public/My%20Long%20Chat/2019/10/11/chat.ttl 403 (User Unauthorized)
```
```
infinite.js:44 
createIfNotExists doc FAILED: <https://khoward.dev.inrupt.net/public/My%20Long%20Chat/2019/10/11/chat.ttl>: Error: Web error: 403 (User Unauthorized) on PUT of <https://khoward.dev.inrupt.net/public/My%20Long%20Chat/2019/10/11/chat.ttl>
```
```
fetcher.js:1230 
Uncaught (in promise) Error: Web error: 403 (User Unauthorized) on PUT of <https://khoward.dev.inrupt.net/public/My%20Long%20Chat/2019/10/11/chat.ttl>
```

## Dev Notes
Ruben proposed (successfully) that the /settings/prefs/.ttl.acl file should be updated to read:
```
@prefix : <#>.
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix c: </profile/card#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

:owner
acl:accessTo <prefs.ttl>; acl:agent c:me; acl:mode acl:Control, acl:Read, acl:Write.

# The public has read permissions
<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;
    acl:accessTo <prefs.ttl>;
    acl:mode acl:Read, acl:Write.
```

**Comment by michielbdejong** [comment]
Making the user's preferences public sounds like quite a radical solution, with negative consequences.
You could probably add that other pod as a trusted app. Let me try to reproduce.

**Comment by michielbdejong** [comment]
Continued in ^

**Comment by michielbdejong** [comment]
I tested this and after adding Moe's pod as a trusted app, Joe was able to write a message in
https://tic-tac-moe.inrupt.net/private/long-chat/
user: tic-tac-joe
pwd: 123
