### ISSUE TITLE
Sharing Permissions not displayed

### ISSUE THREAD

**Issue by brownhoward** [SolidOS/solid-panes#193]
In dev.inrupt.net, when navigating to the Sharing pane in the Data Browser, I do not see the Sharing permissions by group, just the **Stop specific sharing for this folder** button:
![Image1](https://user-images.githubusercontent.com/45850928/67983155-7da6f400-fbfa-11e9-8d79-82a585e3334a.jpg)

## To Replicate
1. Log into a Pod on server dev.inrupt.net.
2. Navigate to a resource.
3. Display the Sharing pane for the resource.

## Expected
1. The Sharing permissions for Owners, Editors, etc. are displayed.

## Actual
1. The Sharing permissions are not displayed.
2. Error is seen in the Console:
```Uncaught (in promise) TypeError: Cannot read property 'http://www.w3.org/ns/auth/acl#Append
http://www.w3.org/ns/auth/acl#Control
http://www.w3.org/ns/auth/acl#Read
http://www.w3.org/ns/auth/acl#Write' of undefined
    at b (acl-control.js:101)
    at acl-control.js:1128
    at acl.js:423
    at acl.js:453
    at fetcher.js:938
```

**Comment by Vinnl** [comment]
@timbl Looks like this commit is the issue: https://github.com/solid/solid-ui/commit/5afb141378f195f395f249258a7fd02768334ada, which was added by your request: https://github.com/solid/solid-ui/pull/123#pullrequestreview-291249392.

Specifically, `byCombo` appears to be referenced in quite a few locations still, and potentially `box[defaultOrMain]` as well. Although `defaultOrMain` would always have had the value `'main'` before [this commit](https://github.com/solid/solid-ui/commit/17b7f24136e2f97d748907062c155f6020df3bf6), so I'm not sure what it's supposed to do. Could you clarify the required behaviour, and what code should be put back into place, if any?
