### ISSUE TITLE
Cannot access Sharing panel for inbox

### ISSUE THREAD

**Issue by michielbdejong** [SolidOS/solid-panes#194]
I tried this with users tic-tac-joe, tic-tac-moe, and example-user .inrupt.net, in all cases I saw 

The https://example-user.inrupt.net/inbox/.acl looks like this:
```turtle
# ACL resource for the profile Inbox

@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#owner>
    a acl:Authorization;

    acl:agent
        <https://example-user.inrupt.net/profile/card#me>;

    acl:accessTo <./>;
    acl:default <./>;

    acl:mode
        acl:Read, acl:Write, acl:Control.

# Public-appendable but NOT public-readable
<#public>
    a acl:Authorization;

    acl:agentClass foaf:Agent;  # everyone

    acl:accessTo <./>;

    acl:mode acl:Append.
```

But when I try to access the Sharing pane for /inbox, I see an error in the console:

<img width="1416" alt="Screenshot 2019-11-05 11 49 45" src="https://user-images.githubusercontent.com/408412/68201621-641ef700-ffc2-11e9-97d2-6333eb62a31b.png">

**Comment by Vinnl** [comment]
I think this is a duplicate of #193, right?

**Comment by brownhoward** [comment]
It is indeed a duplicate. Closing this issue.
