### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by michielbdejong** [SolidOS/solid-panes#216]
I saw the following while running `npm install`:
```sh
~/gh/solid/solid-panes $ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @types/rdflib@1.0.5: This is a stub types definition. rdflib provides its own type definitions, so you do not need this installed.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated text-encoding@0.6.4: no longer maintained
```

Though probably not harmful, these look bad to new contributors. I'll see if I can follow up each of those 5 recommendations.

**Comment by michielbdejong** [comment]
First three fixed.
Fourth continued in https://github.com/solid/solid-ui/issues/192
Fifth continued in https://github.com/solid/solid-panes/issues/219

**Comment by Vinnl** [comment]
@michielbdejong w.r.t.

> npm WARN deprecated @types/rdflib@1.0.5: This is a stub types definition. rdflib provides its own type definitions, so you do not need this installed.

See https://github.com/linkeddata/rdflib.js/issues/369#issuecomment-581138694 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42044. `@types/rdflib` shouldn't be removed, just pinned to the non-stub version (or await the PR to DT to be merged). When rdflib releases a new version with TS support included and you upgrade to that, at that point can the type definitions be removed. Apologies for the confusion.

**Comment by megoth** [comment]
Since three of five are fixed, and the two remaining are separate issues, can we close this issue?

Edit: See now that you're waiting for https://github.com/solid/solid-panes/pull/218 to be reviewed/fixed. Added it to todo-list.

**Comment by timea-solid** [comment]
was fixed already before. But to make sure I checked and it is also fixed in the newest: https://github.com/solid/solidos/issues/134
