### ISSUE TITLE
Travis build fails in deploy step

### ISSUE THREAD

**Issue by michielbdejong** [SolidOS/solid-panes#217]
In https://travis-ci.org/solid/solid-panes/jobs/645705613 it was still passing:
![Screenshot 2020-02-07 12 25 14](https://user-images.githubusercontent.com/408412/74025766-fb6e5e80-49a4-11ea-9439-707192a82145.png)

**Comment by michielbdejong** [comment]
But in https://travis-ci.org/solid/solid-panes/builds/647278318 the build errored without a very clear explanation:
![Screenshot 2020-02-07 12 29 31](https://user-images.githubusercontent.com/408412/74026026-8a7b7680-49a5-11ea-80da-490952957341.png)

**Comment by michielbdejong** [comment]
Note that Travis distinguishes between 'Build errored (!)' and 'Build failed (x)':
![Screenshot 2020-02-07 12 32 09](https://user-images.githubusercontent.com/408412/74028866-b3066f00-49ab-11ea-8123-5ca6ed6df71c.png)

**Comment by timea-solid** [comment]
We use GitHub CI now
