### ISSUE TITLE
Travis step for npm deploy is failing

### ISSUE THREAD

**Issue by michielbdejong** [SolidOS/solid-panes#220]
See #215 for attempts to get it working.
For now, I commented it out #214 in so that we can keep working on the code.
We need to fix this soon because right now nothing will be deployed to npm.
I looked at it for quite some time and don't know what else to try; maybe someone
else wants to have a go or can help?

**Comment by michielbdejong** [comment]
Ah wait, there's a triangle you can expand!
<img width="1035" alt="Screenshot 2020-02-07 15 21 28" src="https://user-images.githubusercontent.com/408412/74036945-91ae7e80-49bd-11ea-8351-49b4653855f0.png">
Will find out what happened there.

**Comment by bourgeoa** [comment]
travis replaced by github actions
