### ISSUE TITLE
Error: Cannot mint new - missing newInstance

### ISSUE THREAD

**Issue by tmciver** [SolidOS/solid-panes#34]
# Summary

When attempting to create a new address book, the error `TypeError: Cannot read property 'uri' of null` is shown.

---

# Steps to Reproduce
1. Click "Public Folder" from your account home page on solid.community.
2. Click the green plus sign.
3. Select "Make new Address Book".
4. Enter a name in the text box.
5. Click the green check mark.

Error is displayed in browser.

**Comment by melvincarvalho** [comment]
When I try this now, I get no error, but also no address book!  Curious!

**Comment by tmciver** [comment]
That is strange.  I'll see if I can have a look tomorrow.

**Comment by Vinnl** [comment]
This bug was fixed in d356d18f2c88ae21899b4636aaca74aed0873627, and the address book project has since moved to https://github.com/solid/contacts-pane.
