### ISSUE TITLE
Introduce an .editorconfig file

### ISSUE THREAD

**Issue by johanbove** [SolidOS/solid-panes#47]
Noticed that some files do not have a uniform structure in regards to spaces vs tabs etc.

An ``.editorconfig`` file can help mitigate this.

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

See https://editorconfig.org/

This would help keep a consistent structure within the source code.

**Comment by melvincarvalho** [comment]
We actually want all our code to work with [standard](https://standardjs.com/)

**Comment by johanbove** [comment]
That’s interesting. Hadn’t seen Standard yet. I was wondering what that “npm run standard” was for :-) I’ll set it up on my dev machine and I’ll pay more attention next time to the coding guidelines!

**Comment by melvincarvalho** [comment]
standard --fix

is your friend!
