### ISSUE TITLE
Javascript error makes profile "plus" icon nonfunctional

### ISSUE THREAD

**Issue by pangolingo** [SolidOS/solid-panes#65]
When I press the "plus" icon on one of my profile screens (https://pangolingo.inrupt.net/profile/card#me or https://pangolingo.inrupt.net/profile/card#id1553178756159) it does nothing. A Javascript error appears in the console.

<img width="966" alt="Screen Shot 2019-03-28 at 10 27 27 AM" src="https://user-images.githubusercontent.com/1423865/55170534-b783b980-5144-11e9-9ef9-162452a3bf99.png">

<img width="893" alt="Screen Shot 2019-03-28 at 10 27 51 AM" src="https://user-images.githubusercontent.com/1423865/55170556-c1a5b800-5144-11e9-8db3-6299011b26aa.png">

I think my profile may have gotten into a weird state: Chrome autocomplete somehow blew away most of the fields (that's a whole other issue).

**Comment by angelo-v** [comment]
Did this work some day? What is the expected behaviour? I dived into a bunch of old spaghetti code and could not make any sense of it. @timbl Can you give some historical context? :)
