### ISSUE TITLE
Implement conventions for panes that facilitate separation of concern

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#72]
Some panes are difficult to understand today for various reasons: Some files are huge (close to 1000 SLOC), some functions are dependent on specific scoping, and some are very much dependent on intricate ways of manipulating the DOM.

We suggest introducing patterns/techniques and tools that are reused across the various panes to make it easier to get an overview of what a pane does.

A technology that might be of interest here is Web Components, that might allow us to create reusable components that can be reused across panes, perhaps even in other projects. A tool that might be of interest here is Stencil, which might make it easier for us to create web components (which could be easily ported to major frameworks as well).

*Action items*

- Find a pattern that faciliates a sensible separation of concern for panes
- Make the pattern a convention across all panes
- Optional: Make use of Web Components
- Optional: Make use of Stencil

**Comment by Vinnl** [comment]
I'm going to use this comment as a notepad to keep track of the I encounter that Panes concern themselves with, to inform the pattern design.

Feedback on e.g. things I might've missed is welcome :)

## Communication Data Browser ➡️ Pane

- An RDFLib node representing the current resource
- A DOM element that the Pane can render into
- The currently authenticated user, if any (and perhaps a way to get notified when the user logs in or out?)
- Request to create a new resource of the Pane's data type (question: should this even be the responsibility of the Pane? If multiple Panes operate on the same data type, why would they need to duplicate the creation code?)

## Communication Pane ➡️ Data Browser

- Navigation to other resources (and subsequent loading of the relevant pane(s)) - currently done through [`GotoSubject`](https://github.com/solid/solid-panes/blob/da10b1a076fa997ca0fb19da72b346f51268aa53/outline/manager.js#L1618)
- A label representing the current resource in the Pane's terms
- An icon representing the Pane
- Notifications? - Haven't seen this used yet, but can imagine this being desirable.

**Comment by megoth** [comment]
We've decided to continue our work on the data browser using React to facilitate separation of concern in React.

We will keep the work done in the other experiments so that others may choose these helper tools if they want for their work on panes.
