### ISSUE TITLE
Introduce linting to our TypeScript code

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#86]
We should introduce linting for TypeScript to ensure a common code style.

We are using [Standard JS](https://standardjs.com/) to lint our JavaScript code today, and this is a library used in many other Solid projects (meaning projects living in the Solid GitHub organization). Lets see if there are any linters out there with a configuration setup that are similar to Standard JS, so that we might have more harmony between our JS and TS code.

**Comment by Vinnl** [comment]
ESLint has [a Standard preset](https://www.npmjs.com/package/eslint-config-standard), is widely used, and [is the focus of the TypeScript team](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), so it seems to me that that would be the way to go?

(It appears that that's what Standard actually uses under the hood. However, with [the additional ceremony to support TypeScript](https://standardjs.com/#typescript), I'm not sure whether using Standard vs ESLint directly still has any advantages?)

(It's only a linter though, and doesn't automatically fix your code. There's [prettier-standard](https://www.npmjs.com/package/prettier-standard) if that's what we want, but that appears to be a fork of Prettier and less widely used, so I'm not sure if we want to run the risk of it becoming unmaintained.)

**Comment by megoth** [comment]
Prettier is interesting, but not what we want right now I think, as we want to align with other projects to make it easier for people that contributes to these repos more sporadically
