### ISSUE TITLE
Error when including space in phone number

### ISSUE THREAD

**Issue by brownhoward** [SolidOS/solid-panes#89]
When editing your Profile, the Data Browser allow spaces to be included in the middle of the phone number (e.g. "617 123 4567"), but then an error is generated when the Data Browser attempts to write the phone number to the Pod:

```
named-node.js:62 Uncaught Error: Error: NamedNode IRI "tel:+1617 456-8620" must not contain unencoded spaces.
    at new t (named-node.js:62)
    at t.value (formula.js:570)
    at HTMLInputElement.<anonymous> (index.js:861)
t @ named-node.js:62
value @ formula.js:570
(anonymous) @ index.js:861
```
Could just update the regex to not allow spaces in the middle of the phone number.

**Comment by megoth** [comment]
Think this is part of the profilePane - either I or @Vinnl will give this is a go 😸

**Comment by megoth** [comment]
This was fixed in https://github.com/solid/solid-ui/pull/65 and pushed to NPM in https://github.com/solid/solid-ui/releases/new?tag=v0.12.2
