### ISSUE TITLE
How should the data browser treat query values in URIs?

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#90]
The data browser uses the URI as subject throughout its code and while this is technically correct, it creates some weird effects wrt UX. 

E.g. `https://megoth.localhost:8443/profile/card#me` and `https://megoth.localhost:8443/profile/card?foo#me` are two different URIs, but the Solid server will provide the same response. They are presented different though, since a lot of panes won't be loaded when viewing `https://megoth.localhost:8443/profile/card?foo#me` since there is no subject with that URI.

Is this the correct way to handle this, or should we change this? We could do it as part of the revamp process, to make sure that everything is handled correctly throughout the various panes.

**Comment by Vinnl** [comment]
It sounds like the correct way to me? Just like regular webpages, appending a query string makes it a different URL that can return different content, but does often return the same content.

They are also different URI's, so many panes are no longer applicable and hence should not be shown.

(That said, we might want to consider a better "falback" pane (or perhaps not even a pane at all, but just default behaviour of the data browser) that is shown for resources that are not containers, and for which no pane is applicable - e.g. like the 404 page on a website, with links to resources the user might be looking for.)

**Comment by pmcb55** [comment]
Hi Arne, I think it's a good question! 

Personally (and I could be very wrong here), I but I've always treated the IRI part to be everything up to, but **not** including the question mark. So I'm saying the opposite of Vincent - I treat the query param as just 'context' associated with the request (exactly as I treat HTTP headers as context, and cookies as context) - so both 'https://ex.com/foo' and 'https://ex.com/foo?bar' are referring to exactly the **same** resource, identified by the IRI 'https://ex.com/foo'.

It would be good to get clarity on this question though, as my assumption implies that applying an ACL to 'https://ex.com/foo?bar' actually applies it to 'https://ex.com/foo' (but does so in the 'context' of a query param of 'bar', which for a particular service instance might mean something server-specific (like 'notify all my friends of this ACL update', or something).

It also raises the question of whether 'https://ex.com/foo' and 'https://ex.com/foo/' are the same - i.e. they are not, unless your service treats them as the same, i.e. https://tools.ietf.org/html/rfc3986#section-6.2.4 :)

**Comment by timbl** [comment]
The answer in general is clear, that when the client gets a URL it sends everything up to and excluding the hash to the server, then whatever comes back, applies the bit after the hash to what it gets back. So the client doesn't get to guess what any query string means.  I can have URIs for things like   `/event?date=20190516&type=board` if I want, with links to other events in the RDF returned

It's a reasonable question to ask, because the query string syntax is designed from when an HTML form lets the client in on the structure and lets the client construct that bit itself.     But that is  brief lapse of the opacity.   When the databrowser is  displaying a thing, it can't assume that it was generated by any particular form.

It is true that some servers strip off the query string, but we can never know that they do as a client.

**Comment by megoth** [comment]
For me this comes down to how the data browser should represent the resource that is returned from the Solid server. 

This is a proposal that makes most sense in my mind: In the context of the Solid data browser (working with resources served via a Solid server implementation) *the subject of a URI* is either *a document* or *a fragment within that document*. It is the subject that is at the center, and what the data browser focuses on wrt deciding which panes to load and make available.

As @timbl says, the full URI is still sent to the server (excluding the hash), but for the purpose of the data browser is *the subject* that the data browser is focused on presenting is either the document or a fragment.

This would still enable various representations that might result from varying query parameters, just as a search document would represent various hits based on a search.

*Examples:*

* `http://ex.com/foo` - the subject refers to _document foo_
* `http://ex.com/foo#bar` - the subject refers _fragment bar_ within _document foo_
* `http://ex.com/foo?baz` - the subject refers to _document foo_
* `http://ex.com/foo?baz#bar` - the subject refers _fragment bar_ within _document foo_

Now, http://ex.com/foo?baz and http://ex.com/foo#bar?baz could still present varying results, such as more links to other events, but the subject that the data browser would focus on, which sets the basis for which panes are loaded are still http://ex.com/foo and http://ex.com/foo#bar respectively.

As a sidenote, this would also make it possible to use query parameters to refer to specific panes, as proposed in https://github.com/solid/solid-panes/issues/92 (heck, you could even refer to multiple panes at the same time).

**Comment by Vinnl** [comment]
So what happens if a Pod server decides to serve different content for `http://ex.com/foo.ttl` and `http://ex.com/foo.ttl?bar=baz`, with a requested `Content-Type` of `text/turtle`? What should the data browser do?

**Comment by megoth** [comment]
It would still reason over the graph that is represented in the returned TTL-resource, and load the panes pertaining to _the subject_ http://ex.com/foo.ttl.

**Comment by RubenVerborgh** [comment]
Wow, this can't be right.

In `https://megoth.localhost:8443/profile/card#me?foo`, the `?foo` does not have any meaning. https://tools.ietf.org/html/rfc3986#section-3

**Comment by megoth** [comment]
> Wow, this can't be right.
> 
> In `https://megoth.localhost:8443/profile/card#me?foo`, the `?foo` does not have any meaning. https://tools.ietf.org/html/rfc3986#section-3

Oh, had forgotten the order of the URI, so yes, https://megoth.localhost:8443/profile/card#me?foo does not make sense. Have updated my posts in this thread that used the wrong ordering.

But I still think that the subject of the URI that the browser should focus on presenting is `/card` for both `/card` and `/card?foo` and `/card#me` for both `/card#me` and `/card?foo#me`. Or is this faulty assumption?

(Btw, I checked how the browser and a simple [Node HTTP server](https://stackoverflow.com/questions/6084360/using-node-js-as-a-simple-web-server) to test whether `/?foo#me` and `/#me?foo` are handled differently, and they certainly are (`/?foo` being the requested URI in the former, `/` in the latter, and the hash parsed in the browser being `me` in the former and `me?foo` in the latter).)

**Comment by RubenVerborgh** [comment]
> But I still think that the subject of the URI that the browser should focus on presenting is `/card` for both `/card` and `/card?foo` and `/card#me` for both `/card#me` and `/card?foo#me`. Or is this faulty assumption?

The browser should not make any assumption about `?`. There is no spec that allows us to do so. `/card` and `/card?foo` might be entirely different resources; nothing allows us to state something about the relation between the two. So basically [what @timbl said](https://github.com/solid/solid-panes/issues/90#issuecomment-494224819).

**Comment by megoth** [comment]
Have thought about this some days, and I agree that we cannot assume anything from query values. So this discussion is concluded.

But I was hoping to be able to store some states in the URI, specifically to address the [possibility of navigating to specific panes for resources](https://github.com/solid/solid-panes/issues/92). I'll continue that discussion in that issue, and hope people will help me there as well ^_^
